In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
arr = np.array([2,3, 4, 5])

In [4]:
print(arr)

[2 3 4 5]


In [ ]:
arr1 = np.array([
    [1, 2, 3, 4],
    [4, -0.9, 3, 4],
    [7, 8, 0.4, 5],
    [5, 6, 3, 6]
])
print(arr1) # rows start from 0 index , columns also start from index 0.

[[ 1.   2.   3.   4. ]
 [ 4.  -0.9  3.   4. ]
 [ 7.   8.   0.4  5. ]
 [ 5.   6.   3.   6. ]]


In [12]:
arr2 = arr1[1:2, 1:3]
arr2

array([[-0.9,  3. ]])

In [ ]:
# add 1 to every element in arr1 # we can perform any
#  arithmatic operation in the same way as we do in this example
print(arr1 + 1)

[[2.  3.  4.  5. ]
 [5.  0.1 4.  5. ]
 [8.  9.  1.4 6. ]
 [6.  7.  4.  7. ]]


In [14]:
# Data types in numpy
x = np.array([1, 2])
print(x.dtype)

y = np.array([0.4, 3.8])
print(y.dtype)

x = np.array([4, 5], dtype= np.int64)
print(x.dtype)


int64
float64
int64


In [15]:
# maths operations on datatype array

arr1  = np.array([[4, 5], [6, 7], [7, 8]], dtype = np.float64)
arr1

array([[4., 5.],
       [6., 7.],
       [7., 8.]])

In [17]:
print(np.add(arr1, 3))

[[ 7.  8.]
 [ 9. 10.]
 [10. 11.]]


In [ ]:
print(np.sum(arr1)) # add all the elements of array

37.0


In [19]:
# fill array with zeros

arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
# fill array with ones

arr1 = np.ones((4, 5))
arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# fill array with particular number

arr_full = np.full((2, 2), 3)
print(arr_full)

[[3 3]
 [3 3]]


In [23]:
# create a random array

arr_rand = np.random.rand(3, 4)
arr_rand

array([[0.94659886, 0.19151347, 0.14978599, 0.03994289],
       [0.89707223, 0.50227635, 0.11323151, 0.87044764],
       [0.23433933, 0.41303913, 0.08360621, 0.1152648 ]])

In [24]:
# .randint used to create a random array in a specific range of numbers

arr_int = np.random.randint(1 , 10, size=(4, 5))
arr_int

array([[5, 7, 5, 2, 1],
       [9, 9, 9, 7, 1],
       [6, 2, 4, 6, 5],
       [9, 7, 8, 3, 2]], dtype=int32)

In [25]:
## aray with range of values
arr_range = np.arange(0, 10, 2)
print(arr_range)

[0 2 4 6 8]


In [26]:
arr_linspace = np.linspace(0, 1, 5)
print(arr_linspace)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# identity -> matrix with contaning 1's in diagonal side


arr_identity = np.eye(3)
print(arr_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# Diagonal Matrix -> matrix where prvided elements are in diagonal form
arr_diagonal = np.diag([1, 2, 3])
print(arr_diagonal)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
